server:
  port:
jwt:
  secret:
  expiration:
spring:
  datasource:
    username:
    password:
    driver-class-name:
    url:
  jpa:
    hibernate:
      ddl-auto:
springdoc:
  swagger-ui:
    enabled:
    path:
  api-docs:
    path:
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO
    tgb.cryptoexchange: DEBUG